In [1]:
import numpy as np

In [28]:
def taylor_n_terms(x,n):
    N = np.arange(n,dtype=int)+1
    print(N)
    return sum([(x**k)/factorial(k) for k in N])+1
    

In [39]:
def factorial(x):
    result=1
    if (type(x) != np.int32):
        print(f"must be integer, not: {type(x)}")
    elif x > 0 and x <100:
        while(x>1):
            result*=x
            x-=1
    else:
        print("factorial outside range: 1-99")
    return result

In [40]:
factorial(2)

must be integer, not: <class 'int'>


1

In [46]:
num = .4482
taylor_n_terms(num,int(2)), taylor_n_terms(num,3), taylor_n_terms(num,4), taylor_n_terms(num,5)

[1 2]
[1 2 3]
[1 2 3 4]
[1 2 3 4 5]


(1.54864162, 1.563647598028, 1.5653290178660373, 1.5654797403403191)

In [47]:
np.e**num

1.5654917626983131