In [12]:
import numpy as np
from torchvision import datasets
from torchvision.transforms import ToTensor
import torch

In [13]:
state_dict = torch.load('model.pth')


In [14]:
state_dict

OrderedDict([('linear_relu_stack.0.weight',
              tensor([[-0.0003,  0.0192, -0.0294,  ...,  0.0219,  0.0037,  0.0021],
                      [-0.0198, -0.0150, -0.0104,  ..., -0.0203, -0.0060, -0.0299],
                      [-0.0201,  0.0149, -0.0333,  ..., -0.0203,  0.0012,  0.0080],
                      ...,
                      [-0.0215,  0.0106,  0.0308,  ..., -0.0199,  0.0161, -0.0342],
                      [ 0.0350, -0.0297, -0.0037,  ...,  0.0171,  0.0238, -0.0001],
                      [ 0.0085,  0.0223, -0.0324,  ..., -0.0296,  0.0182, -0.0296]])),
             ('linear_relu_stack.0.bias',
              tensor([ 0.0112,  0.0016,  0.0017, -0.0255, -0.0138, -0.0105, -0.0166, -0.0136,
                       0.0042,  0.0343, -0.0148, -0.0309,  0.0098,  0.0320, -0.0351,  0.0314,
                       0.0258,  0.0109])),
             ('linear_relu_stack.2.weight',
              tensor([[ 0.1390, -0.1494, -0.2147,  0.2142,  0.1166, -0.1546, -0.1654,  0.0631,
          

In [15]:
training_data = datasets.MNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)
test_data = datasets.MNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor()
)
bs = 64
epochs = 10

In [ ]:
class NeuralNetwork():
    def __init__(self):
        super().__init__()
        np.zeros