In [1]:
import numpy as np
import torch

In [3]:
state_dict = torch.load('model.pth')


In [4]:
state_dict

OrderedDict([('linear_relu_stack.0.weight',
              tensor([[ 0.0020, -0.0116, -0.0197,  ..., -0.0258, -0.0200,  0.0051],
                      [-0.0153, -0.0114, -0.0103,  ...,  0.0012, -0.0130, -0.0185],
                      [-0.0282,  0.0220, -0.0293,  ..., -0.0230, -0.0346,  0.0207],
                      ...,
                      [-0.0350,  0.0145, -0.0280,  ...,  0.0150,  0.0084, -0.0263],
                      [ 0.0310, -0.0118,  0.0110,  ...,  0.0162,  0.0200,  0.0277],
                      [ 0.0314,  0.0335,  0.0279,  ..., -0.0338, -0.0124, -0.0112]])),
             ('linear_relu_stack.0.bias',
              tensor([ 0.0495,  0.1277,  0.1084,  0.0755,  0.1145,  0.0229,  0.1273,  0.1859,
                       0.2094, -0.0232, -0.0198, -0.0285,  0.0208,  0.0857,  0.0708,  0.0131,
                       0.0147,  0.0709])),
             ('linear_relu_stack.2.weight',
              tensor([[ 4.6498e-01,  1.0387e-01, -5.3761e-01,  3.3065e-01, -5.0023e-01,
                 