In [30]:
import torch
from torch import nn
from torch.utils.data import Dataset
from torchvision import datasets
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt
import seaborn as sns



In [27]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using cpu device


In [28]:
training_data = datasets.MNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)

In [31]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [32]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [33]:
X = torch.rand(1, 28, 28, device=device)
logits = model(X)
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")

Predicted class: tensor([7])


In [37]:
input_image = torch.rand(3,28,28)
print(input_image.size())

torch.Size([3, 28, 28])


In [38]:
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

torch.Size([3, 784])


In [39]:
layer1 = nn.Linear(in_features=28*28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())

torch.Size([3, 20])


In [40]:
print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}")

Before ReLU: tensor([[-1.7121e-01, -1.2728e-01,  4.3475e-01, -6.1671e-02,  2.4696e-03,
          4.0180e-01, -2.0845e-01,  5.4073e-02,  4.9153e-02, -1.1493e-01,
         -9.5329e-02, -1.3882e-01,  2.8641e-01,  4.1953e-02, -9.3595e-02,
         -4.7102e-01,  4.0312e-01, -3.5861e-01, -2.1477e-01, -3.0224e-02],
        [-9.1072e-02, -3.0026e-01,  5.4407e-01, -1.0958e-01,  4.4292e-02,
          1.7552e-01, -1.8718e-01, -9.3589e-02,  1.4897e-01,  9.7476e-02,
         -1.2920e-01, -5.9964e-04,  2.8759e-01, -7.7499e-02, -2.2868e-01,
         -8.6386e-03,  1.5937e-01, -2.7554e-01, -6.0191e-01, -1.3011e-01],
        [-2.2133e-01, -3.3193e-01,  2.8073e-01, -6.5526e-02,  7.5463e-03,
          2.3611e-01, -2.1293e-01, -1.7587e-01,  2.4383e-01, -2.8104e-01,
         -4.2973e-02, -5.6224e-02,  6.0410e-02,  5.4402e-03, -3.1400e-01,
          1.0433e-02,  4.0958e-01, -3.1712e-01, -6.0061e-01, -1.7064e-01]],
       grad_fn=<AddmmBackward0>)


After ReLU: tensor([[0.0000, 0.0000, 0.4348, 0.0000, 0.0025,

In [41]:
seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
)
input_image = torch.rand(3,28,28)
logits = seq_modules(input_image)

In [42]:
softmax = nn.Softmax(dim=1)
pred_probab = softmax(logits)

In [43]:
print(f"Model structure: {model}\n\n")

for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")

Model structure: NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


Layer: linear_relu_stack.0.weight | Size: torch.Size([512, 784]) | Values : tensor([[ 0.0210,  0.0009,  0.0297,  ...,  0.0324, -0.0049,  0.0084],
        [-0.0191,  0.0170, -0.0234,  ...,  0.0256, -0.0146,  0.0325]],
       grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.0.bias | Size: torch.Size([512]) | Values : tensor([-0.0328,  0.0059], grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.2.weight | Size: torch.Size([512, 512]) | Values : tensor([[ 0.0052,  0.0205, -0.0243,  ..., -0.0108,  0.0179, -0.0424],
        [ 0.0274, -0.0342,  0.0049,  ..., -0.0242, -0.0384,  0.0307]],
       grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.2.bias | 

In [44]:
import torch

x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [46]:
x,y,w,b,z,loss

(tensor([1., 1., 1., 1., 1.]),
 tensor([0., 0., 0.]),
 tensor([[-0.6635,  2.1987,  0.0240],
         [ 0.4575, -1.4357, -1.2236],
         [ 0.8148, -0.6067, -2.0898],
         [-0.9950,  0.0081,  1.1100],
         [ 1.1244, -0.6857, -0.7051]], requires_grad=True),
 tensor([ 0.5658, -0.8637,  0.4682], requires_grad=True),
 tensor([ 1.3041, -1.3850, -2.4163], grad_fn=<AddBackward0>),
 tensor(0.6177, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>))