In [2]:
import torch
from torch import nn
from torch.utils.data import Dataset
from torchvision import datasets
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt
import seaborn as sns



In [3]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using cpu device


In [4]:
training_data = datasets.MNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)

In [5]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [6]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [7]:
X = torch.rand(1, 28, 28, device=device)
logits = model(X)
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")

Predicted class: tensor([1])


In [8]:
input_image = torch.rand(3,28,28)
print(input_image.size())

torch.Size([3, 28, 28])


In [9]:
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

torch.Size([3, 784])


In [10]:
layer1 = nn.Linear(in_features=28*28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())

torch.Size([3, 20])


In [11]:
print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}")

Before ReLU: tensor([[ 0.2784,  0.0937, -0.1629, -0.4347, -0.1269,  0.2296, -0.4975, -0.1024,
         -0.1146, -0.1203,  0.0392,  0.4601, -0.0807,  0.0178, -0.0712,  0.0352,
         -0.5448,  0.2492, -0.0454,  0.1353],
        [ 0.1806,  0.1084, -0.3891, -0.3674, -0.0876,  0.6655, -0.3391,  0.0093,
         -0.2763, -0.2109, -0.1867,  0.2171, -0.0393,  0.3841, -0.0263, -0.0585,
         -0.3907,  0.1512, -0.0610,  0.0833],
        [ 0.2691,  0.1675,  0.0238, -0.4040, -0.4664,  0.2043, -0.7587, -0.2572,
          0.2104, -0.3382, -0.4328,  0.5187, -0.1330,  0.0548, -0.1683, -0.0375,
         -0.5034,  0.3652,  0.0374,  0.0058]], grad_fn=<AddmmBackward0>)


After ReLU: tensor([[0.2784, 0.0937, 0.0000, 0.0000, 0.0000, 0.2296, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0392, 0.4601, 0.0000, 0.0178, 0.0000, 0.0352, 0.0000, 0.2492,
         0.0000, 0.1353],
        [0.1806, 0.1084, 0.0000, 0.0000, 0.0000, 0.6655, 0.0000, 0.0093, 0.0000,
         0.0000, 0.0000, 0.2171, 0.0000, 0.3841, 0.00

In [12]:
seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
)
input_image = torch.rand(3,28,28)
logits = seq_modules(input_image)

In [13]:
softmax = nn.Softmax(dim=1)
pred_probab = softmax(logits)

In [14]:
print(f"Model structure: {model}\n\n")

for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")

Model structure: NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


Layer: linear_relu_stack.0.weight | Size: torch.Size([512, 784]) | Values : tensor([[-0.0030,  0.0116, -0.0301,  ..., -0.0041,  0.0329,  0.0201],
        [-0.0141,  0.0275, -0.0006,  ..., -0.0291,  0.0103, -0.0005]],
       grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.0.bias | Size: torch.Size([512]) | Values : tensor([-0.0227, -0.0090], grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.2.weight | Size: torch.Size([512, 512]) | Values : tensor([[-0.0428, -0.0116,  0.0122,  ...,  0.0214, -0.0189,  0.0120],
        [ 0.0069, -0.0195, -0.0348,  ...,  0.0013,  0.0202,  0.0287]],
       grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.2.bias | 

In [15]:
import torch

x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [16]:
x,y,w,b,z,loss

(tensor([1., 1., 1., 1., 1.]),
 tensor([0., 0., 0.]),
 tensor([[ 2.2392, -1.6645,  1.6895],
         [-1.4420, -0.1617, -0.7933],
         [-1.4636, -0.3291,  1.3056],
         [ 0.5669, -0.5242, -0.3325],
         [-1.0510,  1.2621,  0.7391]], requires_grad=True),
 tensor([ 0.1604,  0.9332, -1.0061], requires_grad=True),
 tensor([-0.9902, -0.4842,  1.6023], grad_fn=<AddBackward0>),
 tensor(0.8606, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>))

In [17]:
 print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x00000192EFE26BC0>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x00000192EFE26BC0>
